Vagrant.configure('2') do |config|
  config.vm.box = 'ubuntu/xenial32'
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.synced_folder '../examples', '/var/examples'
  config.vm.synced_folder 'output', '/var/output'
  config.vm.provision 'shell', path: 'setup.sh', privileged: false
end
